package com.fourTL.mailCONSTANT;

public class mail_CONSTANT {

	public String mail_Welcome(String username, String password) {

		String welcome = "<!DOCTYPE html\r\n"
				+ "  PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
				+ "<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n" + "\r\n" + "<head>\r\n"
				+ "  <meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\">\r\n"
				+ "  <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\r\n"
				+ "  <title>PropTech Kenya Welcome Email</title>\r\n"
				+ "  <!-- Designed by https://github.com/kaytcat --><!-- Robot header image designed by Freepik.com -->\r\n"
				+ "  <style type=\"text/css\">\r\n"
				+ "    @import url(https://fonts.googleapis.com/css?family=Nunito);\r\n" + "\r\n"
				+ "    /* Take care of image borders and formatting */\r\n" + "\r\n" + "    img {\r\n"
				+ "      max-width: 600px;\r\n" + "      outline: none;\r\n" + "      text-decoration: none;\r\n"
				+ "      -ms-interpolation-mode: bicubic;\r\n" + "    }\r\n" + "\r\n" + "    html {\r\n"
				+ "      margin: 0;\r\n" + "      padding: 0;\r\n" + "    }\r\n" + "\r\n" + "    a {\r\n"
				+ "      text-decoration: none;\r\n" + "      border: 0;\r\n" + "      outline: none;\r\n"
				+ "      color: #bbbbbb;\r\n" + "    }\r\n" + "\r\n" + "    a img {\r\n" + "      border: none;\r\n"
				+ "    }\r\n" + "\r\n" + "    /* General styling */\r\n" + "\r\n" + "    td,\r\n" + "    h1,\r\n"
				+ "    h2,\r\n" + "    h3 {\r\n" + "      font-family: Helvetica, Arial, sans-serif;\r\n"
				+ "      font-weight: 400;\r\n" + "    }\r\n" + "\r\n" + "    td {\r\n"
				+ "      text-align: center;\r\n" + "    }\r\n" + "\r\n" + "    body {\r\n"
				+ "      -webkit-font-smoothing: antialiased;\r\n" + "      -webkit-text-size-adjust: none;\r\n"
				+ "      width: 100%;\r\n" + "      height: 100%;\r\n" + "      color: #666;\r\n"
				+ "      background: #fff;\r\n" + "      font-size: 16px;\r\n" + "      height: 100vh;\r\n"
				+ "      width: 100%;\r\n" + "      padding: 0px;\r\n" + "      margin: 0px;\r\n" + "    }\r\n" + "\r\n"
				+ "    table {\r\n" + "      border-collapse: collapse !important;\r\n" + "    }\r\n" + "\r\n"
				+ "    .headline {\r\n" + "      color: #444;\r\n" + "      font-size: 36px;\r\n" + "    }\r\n" + "\r\n"
				+ "    .force-full-width {\r\n" + "      width: 100% !important;\r\n" + "    }\r\n" + "  </style>\r\n"
				+ "  <style media=\"screen\" type=\"text/css\">\r\n" + "    @media screen {\r\n" + "\r\n"
				+ "      td,\r\n" + "      h1,\r\n" + "      h2,\r\n" + "      h3 {\r\n"
				+ "        font-family: 'Nunito', 'Helvetica Neue', 'Arial', 'sans-serif' !important;\r\n"
				+ "      }\r\n" + "    }\r\n" + "  </style>\r\n"
				+ "  <style media=\"only screen and (max-width: 480px)\" type=\"text/css\">\r\n"
				+ "    /* Mobile styles */\r\n" + "    @media only screen and (max-width: 480px) {\r\n" + "\r\n"
				+ "      table[class=\"w320\"] {\r\n" + "        width: 320px !important;\r\n" + "      }\r\n"
				+ "    }\r\n" + "  </style>\r\n" + "  <style type=\"text/css\"></style>\r\n" + "\r\n" + "</head>\r\n"
				+ "\r\n" + "<body bgcolor=\"#fff\" class=\"body\"\r\n"
				+ "  style=\"padding:20px; margin:0; display:block; background:#ffffff; -webkit-text-size-adjust:none\">\r\n"
				+ "  <table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" height=\"100%\" width=\"100%\">\r\n"
				+ "    <tbody>\r\n" + "      <tr>\r\n"
				+ "        <td align=\"center\" bgcolor=\"#fff\" class=\"\" valign=\"top\" width=\"100%\">\r\n"
				+ "          <center class=\"\">\r\n"
				+ "            <table cellpadding=\"0\" cellspacing=\"0\" class=\"w320\" style=\"margin: 0 auto;\" width=\"600\">\r\n"
				+ "              <tbody>\r\n" + "                <tr>\r\n"
				+ "                  <td align=\"center\" class=\"\" valign=\"top\">\r\n"
				+ "                    <table cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"100%\">\r\n"
				+ "                    </table>\r\n"
				+ "                    <table bgcolor=\"#fff\" cellpadding=\"0\" cellspacing=\"0\" class=\"\"\r\n"
				+ "                      style=\"margin: 0 auto; width: 100%; margin-top: 100px;\">\r\n"
				+ "                      <tbody style=\"margin-top: 15px;\">\r\n"
				+ "                        <tr class=\"\">\r\n" + "                          <td class=\"\">\r\n"
				+ "                            <img alt=\"robot picture\" width=\"350\"\r\n"
				+ "                              src=\"https://lh3.googleusercontent.com/pw/AMWts8BE52AhhQd3jDG4W2RUxzaAq69PcixOhv_nV9VI2IxljwxzDHr6XShIYlSfq1io_5IdAJNePdcUHIDRzYcMJZFaYKf7N4e39CVIwWjUOcjVcW1ra2A4_oecW0PLytJyocXmFFNRAAtQQymNTGxxWD0=w960-h326\">\r\n"
				+ "                          </td>\r\n" + "                        </tr>\r\n"
				+ "                        <tr class=\"\">\r\n"
				+ "                          <td class=\"headline\">Welcome to SevenBee!</td>\r\n"
				+ "                        </tr>\r\n" + "                        <tr>\r\n"
				+ "                          <td>\r\n" + "                            <center class=\"\">\r\n"
				+ "                              <table cellpadding=\"0\" cellspacing=\"0\" class=\"\" style=\"margin: 0 auto;\" width=\"75%\">\r\n"
				+ "                                <tbody class=\"\">\r\n"
				+ "                                  <tr class=\"\">\r\n"
				+ "                                    <td class=\"\" style=\"color:#444; font-weight: 400;\"><br><br>\r\n"
				+ "                                      Bạn đã được đăng ký thành công tài khoản mua sắm.<br>\r\n"
				+ "                                      <br>\r\n"
				+ "                                      Thông tin đăng nhập của bạn được cung cấp dưới đây:\r\n"
				+ "                                      <br> <br>\r\n"
				+ "                                      <span style=\"font-weight:bold;\">Username: &nbsp;</span><span\r\n"
				+ "                                        style=\"font-weight:lighter;\" class=\"\">" + username
				+ "</span>\r\n" + "                                      <br>\r\n"
				+ "                                      <span style=\"font-weight:bold;\">Password: &nbsp;</span><span\r\n"
				+ "                                        style=\"font-weight:lighter;\" class=\"\">" + password
				+ "</span>\r\n" + "                                      <br><br>\r\n"
				+ "                                      <br>\r\n" + "                                    </td>\r\n"
				+ "                                  </tr>\r\n" + "                                </tbody>\r\n"
				+ "                              </table>\r\n" + "                            </center>\r\n"
				+ "                          </td>\r\n" + "                        </tr>\r\n"
				+ "                        <tr>\r\n" + "                          <td class=\"\">\r\n"
				+ "                            <div class=\"\">\r\n"
				+ "                              <a style=\"background-color:#EBB000;border-radius:4px;color:#000000;display:inline-block;font-family:Helvetica, Arial, sans-serif;font-size:18px;font-weight:normal;line-height:50px;text-align:center;text-decoration:none;width:350px;-webkit-text-size-adjust:none;\"\r\n"
				+ "                                href=\"#\">Truy cập tài khoản và bắt đầu trải nghiệm</a>\r\n"
				+ "                            </div>\r\n" + "                            <br>\r\n"
				+ "                          </td>\r\n" + "                        </tr>\r\n"
				+ "                      </tbody>\r\n" + "\r\n" + "                    </table>\r\n" + "\r\n"
				+ "                    <table bgcolor=\"#fff\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\"\r\n"
				+ "                      style=\"margin: 0 auto; margin-bottom: 5px:\">\r\n"
				+ "                      <tbody>\r\n" + "                        <tr>\r\n"
				+ "                          <td class=\"\" style=\"color:#444;\r\n" + "                    \">\r\n"
				+ "                            <p>Mật khẩu đã được tạo tự động, tuy nhiên hãy thay đổi nó ở\r\n"
				+ "\r\n"
				+ "                              <a href=\"#\" style=\"text-decoration: underline; color: blue;\">\r\n"
				+ "                                đây</a>\r\n" + "\r\n" + "                            </p>\r\n"
				+ "                          </td>\r\n" + "                        </tr>\r\n"
				+ "                      </tbody>\r\n" + "                    </table>\r\n"
				+ "                  </td>\r\n" + "                </tr>\r\n" + "              </tbody>\r\n"
				+ "            </table>\r\n" + "          </center>\r\n" + "        </td>\r\n" + "      </tr>\r\n"
				+ "    </tbody>\r\n" + "  </table>\r\n" + "</body>\r\n" + "\r\n" + "</html>";
		return welcome;
	}

	public String mail_WelcomePartner(String username, String password) {
		String welcomePartner = "";
		return welcomePartner;
	}

	public String mail_Camon(String username) {
		String Camon = "<!DOCTYPE html\r\n"
				+ "  PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
				+ "<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n" + "\r\n" + "<head>\r\n"
				+ "  <meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\">\r\n"
				+ "  <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\r\n"
				+ "  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css\" />\r\n"
				+ "\r\n"
				+ "  <!-- Designed by https://github.com/kaytcat --><!-- Robot header image designed by Freepik.com -->\r\n"
				+ "  <style type=\"text/css\">\r\n"
				+ "    @import url(https://fonts.googleapis.com/css?family=Nunito);\r\n" + "\r\n"
				+ "    /* Take care of image borders and formatting */\r\n" + "\r\n" + "    img {\r\n"
				+ "      max-width: 600px;\r\n" + "      outline: none;\r\n" + "      text-decoration: none;\r\n"
				+ "      -ms-interpolation-mode: bicubic;\r\n" + "    }\r\n" + "\r\n" + "    html {\r\n"
				+ "      margin: 0;\r\n" + "      padding: 0;\r\n" + "    }\r\n" + "\r\n" + "    a {\r\n"
				+ "      text-decoration: none;\r\n" + "      border: 0;\r\n" + "      outline: none;\r\n"
				+ "      color: #bbbbbb;\r\n" + "    }\r\n" + "\r\n" + "    a img {\r\n" + "      border: none;\r\n"
				+ "    }\r\n" + "\r\n" + "    /* General styling */\r\n" + "\r\n" + "    td,\r\n" + "    h1,\r\n"
				+ "    h2,\r\n" + "    h3 {\r\n" + "      font-family: Helvetica, Arial, sans-serif;\r\n"
				+ "      font-weight: 400;\r\n" + "    }\r\n" + "\r\n" + "    td {\r\n"
				+ "      text-align: center;\r\n" + "    }\r\n" + "\r\n" + "    body {\r\n"
				+ "      -webkit-font-smoothing: antialiased;\r\n" + "      -webkit-text-size-adjust: none;\r\n"
				+ "      width: 100%;\r\n" + "      height: 100%;\r\n" + "      color: #666;\r\n"
				+ "      background: #fff;\r\n" + "      font-size: 16px;\r\n" + "      height: 100vh;\r\n"
				+ "      width: 100%;\r\n" + "      padding: 0px;\r\n" + "      margin: 0px;\r\n" + "    }\r\n" + "\r\n"
				+ "    table {\r\n" + "      border-collapse: collapse !important;\r\n" + "    }\r\n" + "\r\n"
				+ "    .headline {\r\n" + "      color: #444;\r\n" + "      font-size: 36px;\r\n" + "    }\r\n" + "\r\n"
				+ "    .force-full-width {\r\n" + "      width: 100% !important;\r\n" + "    }\r\n" + "\r\n"
				+ "    .facebook-button {\r\n" + "      font-weight: bold;\r\n" + "      background-color: #1877F2;\r\n"
				+ "      ;\r\n" + "      color: white;\r\n" + "      padding: 8px 16px;\r\n" + "      border: none;\r\n"
				+ "      border-radius: 4px;\r\n" + "      text-align: center;\r\n" + "      text-decoration: none;\r\n"
				+ "      display: inline-block;\r\n" + "      font-size: 16px;\r\n" + "      cursor: pointer;\r\n"
				+ "    }\r\n" + "  </style>\r\n" + "  <style media=\"screen\" type=\"text/css\">\r\n"
				+ "    @media screen {\r\n" + "\r\n" + "      td,\r\n" + "      h1,\r\n" + "      h2,\r\n"
				+ "      h3 {\r\n"
				+ "        font-family: 'Nunito', 'Helvetica Neue', 'Arial', 'sans-serif' !important;\r\n"
				+ "      }\r\n" + "    }\r\n" + "  </style>\r\n"
				+ "  <style media=\"only screen and (max-width: 480px)\" type=\"text/css\">\r\n"
				+ "    /* Mobile styles */\r\n" + "    @media only screen and (max-width: 480px) {\r\n" + "\r\n"
				+ "      table[class=\"w320\"] {\r\n" + "        width: 320px !important;\r\n" + "      }\r\n"
				+ "    }\r\n" + "  </style>\r\n" + "  <style type=\"text/css\"></style>\r\n" + "\r\n" + "</head>\r\n"
				+ "\r\n" + "<body bgcolor=\"#fff\" class=\"body\"\r\n"
				+ "  style=\"padding:20px; margin:0; display:block; background:#ffffff; -webkit-text-size-adjust:none\">\r\n"
				+ "  <table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" height=\"100%\" width=\"100%\">\r\n"
				+ "    <tbody>\r\n" + "      <tr>\r\n"
				+ "        <td align=\"center\" bgcolor=\"#fff\" class=\"\" valign=\"top\" width=\"100%\">\r\n"
				+ "          <center class=\"\">\r\n"
				+ "            <table cellpadding=\"0\" cellspacing=\"0\" class=\"w320\" style=\"margin: 0 auto;\" width=\"600\">\r\n"
				+ "              <tbody>\r\n" + "                <tr>\r\n"
				+ "                  <td align=\"center\" class=\"\" valign=\"top\">\r\n"
				+ "                    <table cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"100%\">\r\n"
				+ "                    </table>\r\n"
				+ "                    <table bgcolor=\"#fff\" cellpadding=\"0\" cellspacing=\"0\" class=\"\"\r\n"
				+ "                      style=\"margin: 0 auto; width: 100%; margin-top: 100px;\">\r\n"
				+ "                      <tbody style=\"margin-top: 15px;\">\r\n"
				+ "                        <tr class=\"\">\r\n" + "                          <td class=\"\">\r\n"
				+ "                            <img alt=\"sevenbee logo\" width=\"350\"\r\n"
				+ "                              src=\"https://scontent.fsgn8-4.fna.fbcdn.net/v/t39.30808-6/330314836_746923423560052_2375696856074264193_n.png?stp=dst-png_s960x960&_nc_cat=109&ccb=1-7&_nc_sid=e3f864&_nc_ohc=kEpP-jW7kyMAX-y9EKy&_nc_ht=scontent.fsgn8-4.fna&oh=00_AfCaVwVHJYllzw6nDX27zuFJbwuqooJ2hFXzQStm31j0YA&oe=63F6F4B6\">\r\n"
				+ "                          </td>\r\n" + "                        </tr>\r\n"
				+ "                        <tr class=\"\">\r\n" + "                          <td class=\"headline\">Hi "
				+ username + "!</td>\r\n" + "                        </tr>\r\n" + "                        <tr>\r\n"
				+ "                          <td>\r\n" + "                            <center class=\"\">\r\n"
				+ "                              <table cellpadding=\"0\" cellspacing=\"0\" class=\"\" style=\"margin: 0 auto;\" width=\"85%\">\r\n"
				+ "                                <tbody class=\"\">\r\n"
				+ "                                  <tr class=\"\">\r\n"
				+ "                                    <td class=\"\" style=\"color:#444; font-weight: 400; text-align: justify;\"><br>\r\n"
				+ "                                      Cảm ơn bạn đã đóng góp ý kiến quý giá cho chúng tôi. Chúng tôi rất trân trọng\r\n"
				+ "                                      những ý kiến của người dùng như bạn, và sẽ luôn lắng nghe và đáp ứng nhu cầu của\r\n"
				+ "                                      người dùng.\r\n"
				+ "                                      <br><br>\r\n"
				+ "                                      Cảm ơn bạn một lần nữa. Nếu bạn có bất kỳ câu hỏi hoặc ý kiến khác, xin hãy liên\r\n"
				+ "                                      hệ với chúng tôi. Chúng tôi luôn sẵn sàng hỗ trợ bạn.\r\n"
				+ "                                      <br> <br>\r\n"
				+ "                                      Trân trọng,\r\n"
				+ "                                      <br>\r\n"
				+ "                                      <span style=\"font-weight:bold;\">- Seven Bee Team</span>\r\n"
				+ "                                      <br> <br>\r\n"
				+ "                                      <span style=\"font-weight:bold;\">Email: &nbsp;</span><span\r\n"
				+ "                                        style=\"font-weight:lighter;\" class=\"\">sevenbee.7bee@gmail.com</span>\r\n"
				+ "                                      <span style=\"font-weight:bold; margin-left: 10%;\">Hotline: &nbsp;</span><span\r\n"
				+ "                                        style=\"font-weight:lighter;\" class=\"\">(+84) 9847 724 10</span>\r\n"
				+ "                                      <br><br>\r\n"
				+ "                                      <div style=\"display: flex; align-items: center; justify-content: center;\">\r\n"
				+ "                                        <a href=\"https://www.facebook.com/se7enbee/\" target=\"_blank\"\r\n"
				+ "                                          class=\"facebook-button\">\r\n"
				+ "                                          <img width=\"20\" src=\"https://cdn.iconscout.com/icon/free/png-256/facebook-logo-2019-1597680-1350125.png\" alt=\"\"> Seven Bee\r\n"
				+ "                                        </a>\r\n"
				+ "                                      </div>\r\n" + "                                    </td>\r\n"
				+ "                                  </tr>\r\n" + "                                </tbody>\r\n"
				+ "                              </table>\r\n" + "                            </center>\r\n"
				+ "                          </td>\r\n" + "                        </tr>\r\n"
				+ "                      </tbody>\r\n" + "                    </table>\r\n"
				+ "                  </td>\r\n" + "                </tr>\r\n" + "              </tbody>\r\n"
				+ "            </table>\r\n" + "          </center>\r\n" + "        </td>\r\n" + "      </tr>\r\n"
				+ "    </tbody>\r\n" + "  </table>\r\n" + "</body>\r\n" + "\r\n" + "</html>";
		return Camon;
	}

}
