package com.fourTL.controller.mail.contact;

public class mail_CONSTANT {

	public String mail_order(String username, String source) {

		String welcome = "<!-- © 2018 Shift Technologies. All rights reserved. -->\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"table-layout:fixed;background-color:#f9f9f9\" id=\"bodyTable\">\r\n"
				+ "    <tbody>\r\n"
				+ "        <tr>\r\n"
				+ "            <td style=\"padding-right:10px;padding-left:10px;\" align=\"center\" valign=\"top\" id=\"bodyCell\">\r\n"
				+ "\r\n"
				+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"wrapperBody\" style=\"max-width:600px\">\r\n"
				+ "                    <tbody>\r\n"
				+ "                        <tr>\r\n"
				+ "                            <td align=\"center\" valign=\"top\">\r\n"
				+ "                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"tableCard\" style=\"background-color:#fff;border-color:#e5e5e5;border-style:solid;border-width:0 1px 1px 1px;\">\r\n"
				+ "                                    <tbody>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"background-color:#00d2f4;font-size:1px;line-height:3px\" class=\"topBorder\" height=\"3\">&nbsp;</td>\r\n"
				+ "                                        </tr>\r\n"
				+ "\r\n"
				+ "                                        <tr style=\"margin-top: 1.5em;\">\r\n"
				+ "                                            <td style=\"padding-bottom: 5px; padding-left: 20px; padding-right: 20px;\" align=\"center\" valign=\"top\" class=\"mainTitle\">\r\n"
				+ "                                                <h2 class=\"text\" style=\"color:#000;font-family:Poppins,Helvetica,Arial,sans-serif;font-size:28px;font-weight:500;font-style:normal;letter-spacing:normal;line-height:36px;text-transform:none;text-align:center;padding:0;margin:0;margin-top: 1.5em;\">Hi \""+username+"\"</h2>\r\n"
				+ "                                            </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"padding-bottom: 30px; padding-left: 20px; padding-right: 20px;\" align=\"center\" valign=\"top\" class=\"subTitle\">\r\n"
				+ "                                                <h4 class=\"text\" style=\"color:#999;font-family:Poppins,Helvetica,Arial,sans-serif;font-size:16px;font-weight:500;font-style:normal;letter-spacing:normal;line-height:24px;text-transform:none;text-align:center;padding:0;margin:0\">Xác nhận thanh toán thành công !</h4>\r\n"
				+ "                                            </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"padding-left:20px;padding-right:20px\" align=\"center\" valign=\"top\" class=\"containtTable ui-sortable\">\r\n"
				+ "                                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"tableDescription\" style=\"\">\r\n"
				+ "                                                    <tbody>\r\n"
				+ "                                                        <tr>\r\n"
				+ "                                                            <td style=\"padding-bottom: 20px;\" align=\"center\" valign=\"top\" class=\"description\">\r\n"
				+ "                                                                <p class=\"text\" style=\"color:#666;font-family:'Open Sans',Helvetica,Arial,sans-serif;font-size:14px;font-weight:400;font-style:normal;letter-spacing:normal;line-height:22px;text-transform:none;text-align:center;padding:0;margin:0\">Chúc mừng bạn đã thanh toán thành công tựa game này.</p>\r\n"
				+ "                                                                <p class=\"text\" style=\"color:#666;font-family:'Open Sans',Helvetica,Arial,sans-serif;font-size:14px;font-weight:400;font-style:normal;letter-spacing:normal;line-height:22px;text-transform:none;text-align:center;padding:0;margin:0\">"+source+"</p>\r\n"
				+ "                                                            </td>\r\n"
				+ "                                                        </tr>\r\n"
				+ "                                                    </tbody>\r\n"
				+ "                                                </table>\r\n"
				+ "\r\n"
				+ "                                            </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"font-size:1px;line-height:1px\" height=\"20\">&nbsp;</td>\r\n"
				+ "                                        </tr>\r\n"
				+ "\r\n"
				+ "                                    </tbody>\r\n"
				+ "                                </table>\r\n"
				+ "                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"space\">\r\n"
				+ "                                    <tbody>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"font-size:1px;line-height:1px\" height=\"30\">&nbsp;</td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                    </tbody>\r\n"
				+ "                                </table>\r\n"
				+ "                            </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                </table>\r\n"
				+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"wrapperFooter\" style=\"max-width:600px\">\r\n"
				+ "                    <tbody>\r\n"
				+ "                        <tr>\r\n"
				+ "                            <td align=\"center\" valign=\"top\">\r\n"
				+ "                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"footer\">\r\n"
				+ "                                    <tbody>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"padding-top:10px;padding-bottom:10px;padding-left:10px;padding-right:10px\" align=\"center\" valign=\"top\" class=\"socialLinks\">\r\n"
				+ "                                                <a href=\"#facebook-link\" style=\"display:inline-block\" target=\"_blank\" class=\"facebook\">\r\n"
				+ "                                                    <img alt=\"\" border=\"0\" src=\"http://email.aumfusion.com/vespro/img/social/light/facebook.png\" style=\"height:auto;width:100%;max-width:40px;margin-left:2px;margin-right:2px\" width=\"40\">\r\n"
				+ "                                                </a>\r\n"
				+ "                                                <a href=\"#twitter-link\" style=\"display: inline-block;\" target=\"_blank\" class=\"twitter\">\r\n"
				+ "                                                    <img alt=\"\" border=\"0\" src=\"http://email.aumfusion.com/vespro/img/social/light/twitter.png\" style=\"height:auto;width:100%;max-width:40px;margin-left:2px;margin-right:2px\" width=\"40\">\r\n"
				+ "                                                </a>\r\n"
				+ "                                                <a href=\"#pintrest-link\" style=\"display: inline-block;\" target=\"_blank\" class=\"pintrest\">\r\n"
				+ "                                                    <img alt=\"\" border=\"0\" src=\"http://email.aumfusion.com/vespro/img/social/light/pintrest.png\" style=\"height:auto;width:100%;max-width:40px;margin-left:2px;margin-right:2px\" width=\"40\">\r\n"
				+ "                                                </a>\r\n"
				+ "                                                <a href=\"#instagram-link\" style=\"display: inline-block;\" target=\"_blank\" class=\"instagram\">\r\n"
				+ "                                                    <img alt=\"\" border=\"0\" src=\"http://email.aumfusion.com/vespro/img/social/light/instagram.png\" style=\"height:auto;width:100%;max-width:40px;margin-left:2px;margin-right:2px\" width=\"40\">\r\n"
				+ "                                                </a>\r\n"
				+ "                                                <a href=\"#linkdin-link\" style=\"display: inline-block;\" target=\"_blank\" class=\"linkdin\">\r\n"
				+ "                                                    <img alt=\"\" border=\"0\" src=\"http://email.aumfusion.com/vespro/img/social/light/linkdin.png\" style=\"height:auto;width:100%;max-width:40px;margin-left:2px;margin-right:2px\" width=\"40\">\r\n"
				+ "                                                </a>\r\n"
				+ "                                            </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"padding: 10px 10px 5px;\" align=\"center\" valign=\"top\" class=\"brandInfo\">\r\n"
				+ "                                                <p class=\"text\" style=\"color:#bbb;font-family:'Open Sans',Helvetica,Arial,sans-serif;font-size:12px;font-weight:400;font-style:normal;letter-spacing:normal;line-height:20px;text-transform:none;text-align:center;padding:0;margin:0\">©&nbsp;Vespro Inc. | 800 Broadway, Suite 1500 | New York, NY 000123, USA.</p>\r\n"
				+ "                                            </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"padding: 0px 10px 20px;\" align=\"center\" valign=\"top\" class=\"footerLinks\">\r\n"
				+ "                                                <p class=\"text\" style=\"color:#bbb;font-family:'Open Sans',Helvetica,Arial,sans-serif;font-size:12px;font-weight:400;font-style:normal;letter-spacing:normal;line-height:20px;text-transform:none;text-align:center;padding:0;margin:0\"> <a href=\"#\" style=\"color:#bbb;text-decoration:underline\" target=\"_blank\">View Web Version </a>&nbsp;|&nbsp; <a href=\"#\" style=\"color:#bbb;text-decoration:underline\" target=\"_blank\">Email Preferences </a>&nbsp;|&nbsp;\r\n"
				+ "                                                    <a href=\"#\" style=\"color:#bbb;text-decoration:underline\" target=\"_blank\">Privacy Policy</a>\r\n"
				+ "                                                </p>\r\n"
				+ "                                            </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"padding: 0px 10px 10px;\" align=\"center\" valign=\"top\" class=\"footerEmailInfo\">\r\n"
				+ "                                                <p class=\"text\" style=\"color:#bbb;font-family:'Open Sans',Helvetica,Arial,sans-serif;font-size:12px;font-weight:400;font-style:normal;letter-spacing:normal;line-height:20px;text-transform:none;text-align:center;padding:0;margin:0\">If you have any quetions please contact us <a href=\"#\" style=\"color:#bbb;text-decoration:underline\" target=\"_blank\">support@mail.com.</a>\r\n"
				+ "                                                    <br> <a href=\"#\" style=\"color:#bbb;text-decoration:underline\" target=\"_blank\">Unsubscribe</a> from our mailing lists</p>\r\n"
				+ "                                            </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"font-size:1px;line-height:1px\" height=\"30\">&nbsp;</td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                    </tbody>\r\n"
				+ "                                </table>\r\n"
				+ "                            </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                        <tr>\r\n"
				+ "                            <td style=\"font-size:1px;line-height:1px\" height=\"30\">&nbsp;</td>\r\n"
				+ "                        </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                </table>\r\n"
				+ "            </td>\r\n"
				+ "        </tr>\r\n"
				+ "    </tbody>\r\n"
				+ "</table>";
		return welcome;
	}

}
