package com.fourTL.util;

public enum PageType {
	HOMEPAGE, SITE_PRODUCT, SITE_SHOPPINGCART, SITE_CHECKOUT, SITE_SHOP, SITE_LOGIN,SITE_LOGIN_PARTNER,SITE_USERPROFILE, SITE_PARTNER, SITE_ABOUTUS, SITE_CONTACT,
	
	ADMIN_WAREHOUSE, ADMIN_CUSTOMER, ADMIN_CHART,
}
